import type { Tables, TablesInsert, TablesUpdate } from './database.types';

export const COMMITMENT_TYPES = {
  ROUTINE: 'routine',
  TASK: 'task',
} as const;

export type CommitmentType = typeof COMMITMENT_TYPES[keyof typeof COMMITMENT_TYPES];

export const DEADLINE_TYPES = {
  END_OF_DAY: 'end_of_day',
  SPECIFIC_TIME: 'specific_time',
} as const;

export type DeadlineType = typeof DEADLINE_TYPES[keyof typeof DEADLINE_TYPES];

export interface CommitmentFormState {
  title: string;
  type: CommitmentType;
  checkInDays: boolean[];
  dueDate: Date | null;
  amountCents: number;
  deadlineType: DeadlineType;
  deadlineTime: string;
}

/**
 * Underlying table rows generated by Supabase.
 * Re-exported with friendly aliases so screens/hooks can import a single
 * canonical type per table.
 */
export type RoutineRow = Tables<'routines'>;
export type TaskRow = Tables<'tasks'>;
export type CheckInRow = Tables<'check_ins'>;
export type ChargeRow = Tables<'charges'>;
export type ProfileRow = Tables<'profiles'>;

export type RoutineInsert = TablesInsert<'routines'>;
export type RoutineUpdate = TablesUpdate<'routines'>;
export type TaskInsert = TablesInsert<'tasks'>;
export type TaskUpdate = TablesUpdate<'tasks'>;
export type ProfileUpdate = TablesUpdate<'profiles'>;
export type CheckInInsert = TablesInsert<'check_ins'>;

/**
 * Discriminated union row from the `commitments` view.
 * The view UNIONs `routines` and `tasks`; we narrow per-shape:
 *  - Routine rows expose `check_in_days` (due_date / checked_in are NULL)
 *  - Task rows expose `due_date` + `checked_in` (check_in_days is NULL)
 * `deadline_type` is narrowed from the underlying `text` column to our
 * known enum-like literal union.
 */
export type Routine = RoutineRow & {
  type: typeof COMMITMENT_TYPES.ROUTINE;
  due_date: null;
  checked_in: null;
  deadline_type: DeadlineType;
};

export type Task = TaskRow & {
  type: typeof COMMITMENT_TYPES.TASK;
  check_in_days: null;
  deadline_type: DeadlineType;
};

export type Commitment = Routine | Task;

/**
 * UI-only state layered on top of a Commitment when displayed in today's list.
 */
export interface CheckInState {
  isCheckedIn: boolean;
  checkInId: string | null;
  isMissed: boolean;
}
